
EPSILON = 1e-8

##  Time  ##
SECONDS_PER_MINUTE = MINUTES_PER_HOUR = 60
MICROSECONDS_PER_MILLISECOND = MILLISECONDS_PER_SECOND = 1000
MICROSECONDS_PER_SECOND = MICROSECONDS_PER_MILLISECOND * MILLISECONDS_PER_SECOND  # 1,000,000

##  Strings  ##
MINUTE_STR, MINUTES_STR = "minute", "minutes"
SECOND_STR, SECONDS_STR = "second", "seconds"
MILLISECOND_STR, MILLISECONDS_STR = "millisecond", "milliseconds"
MICROSECOND_STR, MICROSECONDS_STR = "microsecond", "microseconds"

SAMPLE_STR, SAMPLES_STR = "sample", "samples"
LABEL_STR, LABELS_STR = "label", "labels"
EVENT_STR, EVENTS_STR = "event", "events"

ID_STR = "id"
SUBJECT_STR = "subject"
TRIAL_STR = "trial"
SUBJECT_ID_STR, TRIAL_ID_STR = f"{SUBJECT_STR}_{ID_STR}", f"{TRIAL_STR}_{ID_STR}"

TIME_STR = "time"
